[package]
name = "kernel"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[build-dependencies]
cc = "1.0.83"

[dependencies]
once_cell = { version = "1.19.0", default-features = false }
spin = "0.9.8"
