[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[build]
target = "src/i386-unknown-none.json"

[target.'cfg(target_os = "none")']
runner = "qemu-system-i386 -kernel"

